### ISSUE TITLE
[Bug] Mobile dnd showing up as online with BorderShapes

### ISSUE THREAD

**Issue by slowstab** [GriefMoDz/better-status-indicators#16]
it used to be working fine, this has been a thing for while but i was too lazy to make an issue :D
![24_05_2021-10_29_DiscordCanary_qOJEMTz](https://user-images.githubusercontent.com/36301891/119320342-c8280f80-bc7b-11eb-885a-dc59ab0795cb.png)

**Comment by GriefMoDz** [comment]
Hello! As much as I do appreciate you bringing this forward to me, I'm afraid this isn't a bug linked to "Better Status Indicators". 

I'd advise that you contact the developer of "BorderShapes" to update their theme so that it can take into account the new fill color for the "Do Not Disturb" status that was changed 2 weeks ago from now.

Sorry for the inconvenience caused!

**Comment by slowstab** [comment]
ah i see makes more sense that it would be a theme issue, thank you for the response!
