### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Dan3a** [GriefMoDz/better-status-indicators#42]
## Expected Behavior
Not crash and start powercord

## Current Behavior
Crashes after loading

## Steps to Reproduce
1. Install the better-status-indicator plugin for Powercord
2. Start Discord

**Comment by joelnedev** [comment]
it appears that if you start Powercord without this plugin, readd it to the plugin folder, and refresh for missing plugins, no issues arise until the next refresh/restart.

hope that helps narrow down the problem.

**Comment by GriefMoDz** [comment]
Hey! Thanks for the bug report, and apologies for the delay! I've since corrected this under version 1.15.5 (https://github.com/GriefMoDz/better-status-indicators/commit/2830e01d38d9b41bbd500673a605293abd22cae6). Let me know if it still isn't working and I shall preform some further diagnostics. Cheers!
