### ISSUE TITLE
instantly crashes on replugged when viewing text channels

### ISSUE THREAD

**Issue by HexaRG** [GriefMoDz/better-status-indicators#48]
![image](https://user-images.githubusercontent.com/67880600/182001683-38177cdc-560e-44d5-a663-89ab2b0d2e88.png)

**Comment by Absumm** [comment]
it infinitely reloads for me on replugged, never puts me into discord

**Comment by bop34** [comment]
Me too

**Comment by xNasuni** [comment]
happens for me aswell.

**Comment by Guobmin** [comment]
can confirm this is happening

**Comment by Kloxified** [comment]
Happens for me as well

**Comment by GriefMoDz** [comment]
Hey! Thanks for the bug report, and apologies for the delay! I've since corrected this under version `1.15.9~1` (https://github.com/GriefMoDz/better-status-indicators/commit/b547b27a155e7af78a6d2ff6a1dbde44243118d0). Please let me know if it still isn't working and I shall re-open the issue and preform some further diagnostics. Cheers!
