### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Twizzer** [GriefMoDz/better-status-indicators#50]
Better Status Indicators is still crashing discord and forcing a crash loop, only way to fix it was to remove the plugin from the modded discord.

I know you pushed a patch 6 days ago but it isn't fixed and it is still happening.

**Comment by bop34** [comment]
Are you using replugged?

**Comment by Twizzer** [comment]
No I'm using Kernel Mod.

**Comment by GriefMoDz** [comment]
Hey! Thanks for the bug report, and apologies for the delay! I've since corrected this under version `1.15.9~1` (https://github.com/GriefMoDz/better-status-indicators/commit/b547b27a155e7af78a6d2ff6a1dbde44243118d0). Please let me know if it still isn't working and I shall re-open the issue and preform some further diagnostics. Cheers!
